---
title: "Simulation Result Analysis"
author: "Jinyu Luo"
date: "2024-04-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```

# Coverage Probability 

```{r}
load(file = "Outputs/raw_results/coverage_prob.rds")
```

## Full Model

```{r}
kableExtra::kable(full_cp, escape = FALSE, digits = 3, 
                  caption = "True Parameter Coverage Rate from Full Model with 1000 Simulations") %>%
  kable_styling(full_width = F, position = "center") %>% 
  add_header_above(c(" ", "Unadjusted Standard Error" = 7, "Adjusted Standard Error" = 7)) %>% 
  column_spec(8, bold = T) %>% 
  column_spec(15, bold = T) %>% 
  pack_rows("Without Drop out", 1, 3) %>% 
  pack_rows("With Drop outs", 4, 6)
```


## Reduced Model 

```{r}
kableExtra::kable(red_cp, escape = FALSE, digits = 3, 
                  caption = "True Parameter Coverage Rate from Reduced Model with 1000 Simulations") %>%
  kable_styling(full_width = F, position = "center") %>% 
  add_header_above(c(" ", "Unadjusted Standard Error" = 4, "Adjusted Standard Error" = 4)) %>% 
  column_spec(5, bold = T) %>% 
  column_spec(9, bold = T) %>% 
  pack_rows("Without Drop out", 1, 3) %>% 
  pack_rows("With Drop outs", 4, 6)
```


# Without Dropouts

```{r}
load(file = "Outputs/raw_results/withoutDropout.rds")
```

## Visualize the distribution standard errors 
```{r}
se_df <- data.frame(independence = se_res[[1]][[1]][,7], 
                    exchangeable = se_res[[1]][[2]][,7], 
                    ar1 = se_res[[1]][[3]][,7])
plots <- lapply(names(se_df)[1:3], function(col_name) {
  se_df %>%
    ggplot(aes_string(x = col_name)) +
    geom_density() +
    ggtitle(paste("Density of", col_name))
})
do.call(gridExtra::grid.arrange, plots)
```
The density plot suggests that  
1. Non-convergence occurred in exchangeable correlation structure.  
2. Standard errors are distributed from 0 to 0.5. 

# Convergence Selection 
```{r}
se_max <- 0.5
converged <- se_df %>%
  mutate_all(funs(. <= se_max))
converged_list <- lapply(converged, which)

temp_se <- se_res
mod_names <- names(est_res)
corrstr <- names(est_res$full)
for (i in 1:2) {
  for (j in 1:3) {
    idx <- converged_list[[j]]
    se <- temp_se[[i]][[j]][idx,]
    temp_se[[i]][[j]] <- se
    se_density <- density(se)
    plot(se_density, main=paste("Density of Standard Errors for", mod_names[i], 
                                "with", corrstr[j], "correlation.", sep = " "))
  }
}
```

```{r}
temp_est <- est_res
temp_bias <- bias_res
temp_mse <- mse_res
for (i in 1:2) {
  for (j in 1:3) {
    idx <- converged_list[[j]]
    temp_est[[i]][[j]] <- temp_est[[i]][[j]][idx,]
    temp_bias[[i]][[j]] <- temp_bias[[i]][[j]][idx,]
    temp_mse[[i]][[j]] <- temp_mse[[i]][[j]][idx,]
  }
}
```

```{r}
# Results for Full Set of Parameter Estimates
res_cols <- c("Mean Estimate", "SD(Estimate)", "Mean Std. Error", 
              "SD(Std. Error)", "Mean Bias", "Mean MSE")
# 1. Full set of covariates
full_results <- cbind(`True Values` = gee_coef, 
                      est.ind = colMeans(temp_est[[1]]$independence, na.rm = TRUE),
                      sd.ind = apply(temp_est[[1]]$independence, 2, sd, na.rm = TRUE), 
                      se.ind = colMeans(temp_se[[1]]$independence, na.rm = TRUE),
                      se.sd.ind = apply(temp_se[[1]]$independence, 2, sd, na.rm = TRUE),
                      bias.ind = colMeans(temp_bias[[1]]$independence, na.rm = TRUE),
                      mse.ind = colMeans(temp_mse[[1]]$independence, na.rm = TRUE), 
                      est.ex = colMeans(temp_est[[1]]$exchangeable, na.rm = TRUE),
                      sd.ex = apply(temp_est[[1]]$exchangeable, 2, sd, na.rm = TRUE), 
                      se.ex = colMeans(temp_se[[1]]$exchangeable, na.rm = TRUE),
                      se.sd.ex = apply(temp_se[[1]]$exchangeable, 2, sd, na.rm = TRUE),
                      bias.ex = colMeans(temp_bias[[1]]$exchangeable, na.rm = TRUE),
                      mse.ex = colMeans(temp_mse[[1]]$exchangeable, na.rm = TRUE), 
                      est.ar1 = colMeans(temp_est[[1]]$ar1, na.rm = TRUE),
                      sd.ar1 = apply(temp_est[[1]]$ar1, 2, sd, na.rm = TRUE),
                      se.ar1 = colMeans(temp_se[[1]]$ar1, na.rm = TRUE),
                      se.sd.ar1 = apply(temp_se[[1]]$ar1, 2, sd, na.rm = TRUE),
                      bias.ar1 = colMeans(temp_bias[[1]]$ar1, na.rm = TRUE),
                      mse.ar1 = colMeans(temp_mse[[1]]$ar1, na.rm = TRUE)) %>% t()
colnames(full_results) <- param_full
rownames(full_results) <- c("True Value", rep(res_cols, 3))
kableExtra::kable(full_results, escape = FALSE, digits = 3, 
                  caption = "Estimation Results for Full Model without dropout from 1000 Simulations") %>%
  kable_styling(full_width = F, position = "center") %>% 
  column_spec(8, bold = T) %>% 
  pack_rows("Independent", 2, 7) %>% 
  pack_rows("Exchangeable", 8, 13) %>% 
  pack_rows("AR1", 14, 19)
```


```{r, eval=FALSE}
## Convergence -------------------------------------------------
se_threshold <- 5
non_converged <- list()
non_convergence <- matrix(rep(0, 6), nrow = 3, 
                          dimnames = list(corstrs, c("Full", "Reduced")))
# Nested loop structure to go through the lists and sublists
for (i in 1:2) {
  non_converged[[i]] <- list()  # Initialize sub-list for each main list group
  for (j in 1:3) {
    # Apply the condition and store indices of values > threshold
    idx <- which(sapply(se_res[[i]][[j]], function(x) x > se_threshold))
    corname <- corstrs[j]
    n_sim <- length(idx)
    non_convergence[j,i] <- n_sim
    if(!n_sim==0) {
      print(paste("Model set", i, "with", corstrs[j], 
                  "correlation include", "Non-convergence", sep=" "))
    } 
    else{
      non_converged[[i]]$corname <- NULL
    }
  }
}

# Remove non-converged simulations 


## Estimation Results ----------------------------------------------
# Results for Full Set of Parameter Estimates
res_cols <- c("Mean Estimate", "SD(Estimate)", "Mean Std. Error", 
              "SD(Std. Error)", "Mean Bias", "Mean MSE")
# 1. Full set of covariates
full_results <- cbind(`True Values` = gee_coef, 
                      est.ind = colMeans(est_res[[1]]$independence, na.rm = TRUE),
                      sd.ind = apply(est_res[[1]]$independence, 2, sd, na.rm = TRUE), 
                      se.ind = colMeans(se_res[[1]]$independence, na.rm = TRUE),
                      se.sd.ind = apply(se_res[[1]]$independence, 2, sd, na.rm = TRUE),
                      bias.ind = colMeans(bias_res[[1]]$independence, na.rm = TRUE),
                      mse.ind = colMeans(mse_res[[1]]$independence, na.rm = TRUE), 
                      est.ex = colMeans(est_res[[1]]$exchangeable, na.rm = TRUE),
                      sd.ex = apply(est_res[[1]]$exchangeable, 2, sd, na.rm = TRUE), 
                      se.ex = colMeans(se_res[[1]]$exchangeable, na.rm = TRUE),
                      se.sd.ex = apply(se_res[[1]]$exchangeable, 2, sd, na.rm = TRUE),
                      bias.ex = colMeans(bias_res[[1]]$exchangeable, na.rm = TRUE),
                      mse.ex = colMeans(mse_res[[1]]$exchangeable, na.rm = TRUE), 
                      est.ar1 = colMeans(est_res[[1]]$ar1, na.rm = TRUE),
                      sd.ar1 = apply(est_res[[1]]$ar1, 2, sd, na.rm = TRUE),
                      se.ar1 = colMeans(se_res[[1]]$ar1, na.rm = TRUE),
                      se.sd.ar1 = apply(se_res[[1]]$ar1, 2, sd, na.rm = TRUE),
                      bias.ar1 = colMeans(bias_res[[1]]$ar1, na.rm = TRUE),
                      mse.ar1 = colMeans(mse_res[[1]]$ar1, na.rm = TRUE)) %>% t()
colnames(full_results) <- param_full
rownames(full_results) <- c("True Value", rep(res_cols, 3))
kableExtra::kable(full_results, escape = FALSE, digits = 3, 
                  caption = "Estimation Results for Full Model without dropout from 1000 Simulations") %>%
  kable_styling(full_width = F, position = "center") %>% 
  column_spec(8, bold = T) %>% 
  pack_rows("Independent", 2, 7) %>% 
  pack_rows("Exchangeable", 8, 13) %>% 
  pack_rows("AR1", 14, 19)



# Results for Full Set of Parameter Estimates with Drop outs 
res_cols <- c("Mean Estimate", "SD(Estimate)", "Mean Std. Error", "SD(Std. Error)", "Mean Bias", "Mean MSE")
# 1. Full set of covariates
full_results_do <- cbind(`True values` = gee_coef, 
                         est.ind = colMeans(est_do[[1]]$independence, na.rm = TRUE),
                         sd.ind = apply(est_do[[1]]$independence, 2, sd, na.rm = TRUE), 
                         se.ind = colMeans(se_do[[1]]$independence, na.rm = TRUE),
                         se.sd.ind = apply(se_do[[1]]$independence, 2, sd, na.rm = TRUE),
                         bias.ind = colMeans(bias_do[[1]]$independence, na.rm = TRUE),
                         mse.ind = colMeans(mse_do[[1]]$independence, na.rm = TRUE), 
                         est.ex = colMeans(est_do[[1]]$exchangeable, na.rm = TRUE),
                         sd.ex = apply(est_do[[1]]$exchangeable, 2, sd, na.rm = TRUE), 
                         se.ex = colMeans(se_do[[1]]$exchangeable, na.rm = TRUE),
                         se.sd.ex = apply(se_do[[1]]$exchangeable, 2, sd, na.rm = TRUE),
                         bias.ex = colMeans(bias_do[[1]]$exchangeable, na.rm = TRUE),
                         mse.ex = colMeans(mse_do[[1]]$exchangeable, na.rm = TRUE), 
                         est.ar1 = colMeans(est_do[[1]]$ar1, na.rm = TRUE),
                         sd.ar1 = apply(est_do[[1]]$ar1, 2, sd, na.rm = TRUE),
                         se.ar1 = colMeans(se_do[[1]]$ar1, na.rm = TRUE),
                         se.sd.ar1 = apply(se_do[[1]]$ar1, 2, sd, na.rm = TRUE),
                         bias.ar1 = colMeans(bias_do[[1]]$ar1, na.rm = TRUE),
                         mse.ar1 = colMeans(mse_do[[1]]$ar1, na.rm = TRUE)) %>% t()
colnames(full_results_do) <- param_full
rownames(full_results_do) <- c("True Value", rep(res_cols, 3))
kableExtra::kable(full_results_do, escape = FALSE, digits = 3, 
                  caption = "Estimation Results for Full Model with Drop outs from 1000 Simulations") %>%
  kable_styling(full_width = F, position = "center") %>% 
  column_spec(8, bold = T) %>% 
  pack_rows("Independent", 2, 7) %>% 
  pack_rows("Exchangeable", 8, 13) %>% 
  pack_rows("AR1", 14, 19)


# 2. Reduced Covariate set 
reduced_result <- cbind(`True values` = red_gee_coef, 
                        est.ind = colMeans(est_res[[2]]$independence, na.rm = TRUE),
                        sd.ind = apply(est_res[[2]]$independence, 2, sd, na.rm = TRUE), 
                        se.ind = colMeans(se_res[[2]]$independence, na.rm = TRUE),
                        se.sd.ind = apply(se_res[[2]]$independence, 2, sd, na.rm = TRUE),
                        bias.ind = colMeans(bias_res[[2]]$independence, na.rm = TRUE),
                        mse.ind = colMeans(mse_res[[2]]$independence, na.rm = TRUE), 
                        est.ex = colMeans(est_res[[2]]$exchangeable, na.rm = TRUE),
                        sd.ex = apply(est_res[[2]]$exchangeable, 2, sd, na.rm = TRUE), 
                        se.ex = colMeans(se_res[[2]]$exchangeable, na.rm = TRUE),
                        se.sd.ex = apply(se_res[[2]]$exchangeable, 2, sd, na.rm = TRUE),
                        bias.ex = colMeans(bias_res[[2]]$exchangeable, na.rm = TRUE),
                        mse.ex = colMeans(mse_res[[2]]$exchangeable, na.rm = TRUE), 
                        est.ar1 = colMeans(est_res[[2]]$ar1, na.rm = TRUE),
                        sd.ar1 = apply(est_res[[2]]$ar1, 2, sd, na.rm = TRUE),
                        se.ar1 = colMeans(se_res[[2]]$ar1, na.rm = TRUE),
                        se.sd.ar1 = apply(se_res[[2]]$ar1, 2, sd, na.rm = TRUE),
                        bias.ar1 = colMeans(bias_res[[2]]$ar1, na.rm = TRUE),
                        mse.ar1 = colMeans(mse_res[[2]]$ar1, na.rm = TRUE)) %>% t()
colnames(reduced_result) <- red_param
rownames(reduced_result) <- c("True Value", rep(res_cols, 3))
kableExtra::kable(reduced_result, escape = FALSE, digits = 3, 
                  caption = "Estimate Results for Reduced Model without dropouts from 1000 Simulations") %>%
  kable_styling(full_width = F, position = "center") %>% 
  column_spec(5, bold = T) %>% 
  pack_rows("Independent", 2, 7) %>% 
  pack_rows("Exchangeable", 8, 13) %>% 
  pack_rows("AR1", 14, 19)

# Reduced model with drop outs 
reduced_result_do <- cbind(`True values` = red_gee_coef, 
                           est.ind = colMeans(est_do[[2]]$independence, na.rm = TRUE),
                           sd.ind = apply(est_do[[2]]$independence, 2, sd, na.rm = TRUE), 
                           se.ind = colMeans(se_do[[2]]$independence, na.rm = TRUE),
                           se.sd.ind = apply(se_do[[2]]$independence, 2, sd, na.rm = TRUE),
                           bias.ind = colMeans(bias_do[[2]]$independence, na.rm = TRUE),
                           mse.ind = colMeans(mse_do[[2]]$independence, na.rm = TRUE), 
                           est.ex = colMeans(est_do[[2]]$exchangeable, na.rm = TRUE),
                           sd.ex = apply(est_do[[2]]$exchangeable, 2, sd, na.rm = TRUE), 
                           se.ex = colMeans(se_do[[2]]$exchangeable, na.rm = TRUE),
                           se.sd.ex = apply(se_do[[2]]$exchangeable, 2, sd, na.rm = TRUE),
                           bias.ex = colMeans(bias_do[[2]]$exchangeable, na.rm = TRUE),
                           mse.ex = colMeans(mse_do[[2]]$exchangeable, na.rm = TRUE), 
                           est.ar1 = colMeans(est_do[[2]]$ar1, na.rm = TRUE),
                           sd.ar1 = apply(est_do[[2]]$ar1, 2, sd, na.rm = TRUE),
                           se.ar1 = colMeans(se_do[[2]]$ar1, na.rm = TRUE),
                           se.sd.ar1 = apply(se_do[[2]]$ar1, 2, sd, na.rm = TRUE),
                           bias.ar1 = colMeans(bias_do[[2]]$ar1, na.rm = TRUE),
                           mse.ar1 = colMeans(mse_do[[2]]$ar1, na.rm = TRUE)) %>% t()
colnames(reduced_result_do) <- red_param
rownames(reduced_result_do) <- c("True Value", rep(res_cols, 3))
kableExtra::kable(reduced_result_do, escape = FALSE, digits = 3, 
                  caption = "Estimate Results for Reduced Model with dropout from 1000 Simulations") %>%
  kable_styling(full_width = F, position = "center") %>% 
  column_spec(5, bold = T) %>% 
  pack_rows("Independent", 2, 7) %>% 
  pack_rows("Exchangeable", 8, 13) %>% 
  pack_rows("AR1", 14, 19)
```

